package com.katie.cleancodestore;

import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.test.context.junit4.SpringRunner;

import java.util.List;

@RunWith(SpringRunner.class)
@DataJpaTest
public class ProductTests {

    //default implementation is SimpleJpaRepository
    ProductRepository repository;
    Product product;

    @Autowired
    public void setProductRepository(ProductRepository productRepository) {
        this.repository = productRepository;
    }

    @Before
    public void setUp() {
        product = new Product();
        product.setName("Dongle");
        repository.save(product);
    }

    @Test
    public void productShouldReturnCorrectName() {
        Assert.assertEquals("Dongle", product.getName());
    }

    @Test
    public void productShouldBeAddedToDatabase() {
        List<Product> productList = repository.findAll();

        Assert.assertTrue(productList.size() == 1);

        Assert.assertNotNull(repository.findAll());
    }

    @Test
    public void uniqueProductIdsShouldBeAutoGenerated() {
        Product product1 = new Product();
        Product product2 = new Product();

        //ID is generated when you save to repo
        repository.save(product1);
        repository.save(product2);

        System.out.println(product1.getId());
        System.out.println(product2.getId());

        Assert.assertNotNull(product1.getId());
        Assert.assertNotNull(product2.getId());

        Assert.assertNotEquals(product1.getId(), product2.getId());
    }

}
