package com.katie.cleancodestore;

import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.test.context.junit4.SpringRunner;

import java.util.List;

@RunWith(SpringRunner.class)
@DataJpaTest
public class ProductTests {

    //default implementation is SimpleJpaRepository
    private ProductRepository repository;
    private Product dongle = new Product();
    private Product headphones = new Product();
    private Product dongle2 = new Product();

    @Autowired
    public void setProductRepository(ProductRepository productRepository) {
        this.repository = productRepository;
    }

    @Before
    public void setUp() {
//        dongle.setName("Dongle");
//        repository.save(dongle);
//
//        headphones.setName("Headphones");
//        repository.save(headphones);

        ProductSaver.saveProduct("Dongle", 15.99);
        ProductSaver.saveProduct("Headphones", 49.99);
    }

    @Test
    public void productShouldReturnCorrectName() {
        Assert.assertEquals("Dongle", dongle.getName());
        Assert.assertEquals("Headphones", headphones.getName());
    }

    @Test
    public void productShouldBeAddedToDatabase() {
        List<Product> productList = repository.findAll();

        Assert.assertTrue(productList.contains(dongle));
        Assert.assertTrue(productList.contains(headphones));

        Assert.assertNotNull(repository.findAll());
    }

    @Test
    public void uniqueProductIdsShouldBeAutoGenerated() {
        Product product1 = new Product();
        Product product2 = new Product();

        //ID is generated when you save to repo
        repository.save(product1);
        repository.save(product2);

        System.out.println(product1.getId());
        System.out.println(product2.getId());

        Assert.assertNotNull(product1.getId());
        Assert.assertNotNull(product2.getId());

        Assert.assertNotEquals(product1.getId(), product2.getId());
    }

    @Test
    public void productsShouldNotBeDuplicated() {

        ProductSaver.saveProduct("Dongle", 14.99);

        Assert.assertTrue(repository.findAll().contains(dongle));
        Assert.assertFalse(repository.findAll().contains(dongle2));
    }

}
